name: Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build release for'
        required: true
        type: string

jobs:

  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go

    - name: Build AMD64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -installsuffix nocgo -v -o traefik-forward-auth_amd64 ./cmd

    - name: Build ARM
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm GO111MODULE=on go build -a -installsuffix nocgo -v -o traefik-forward-auth_arm ./cmd

    - name: Get tag name
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        else
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        fi

    - name: Get artifact details
      uses: octokit/request-action@v2.3.1
      id: get_release_details
      with:
        route: get /repos/${{ github.repository }}/releases/tags/${{ env.TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          traefik-forward-auth_amd64
          traefik-forward-auth_arm
